repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.2
    hooks:
      - id: isort
  - repo: https://github.com/chewse/pre-commit-mirrors-pydocstyle
    rev: v2.1.1
    hooks:
      - id: pydocstyle
        args: ["--add-select=D213,D404", "--ignore=D202,D212,D406,D407,D203"]
        exclude: "^test|^example"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.780
    hooks:
      - id: mypy
        exclude: "^example|conf.py$"
        additional_dependencies:
          - "sqlalchemy-stubs"
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python3 -m pylint.__main__
        args: [-rn]
        language: system
        types: [python]
        exclude: "^example|conf.py$"
  - repo: https://github.com/prettier/prettier
    rev: "2.0.5"
    hooks:
      - exclude: "^docs.*.yaml$"
        id: prettier
