[tool.poetry]
name = "OpenAlchemy"
version = "2.0.1"
description = "Maps an OpenAPI schema to SQLAlchemy models."
authors = ["David Andersson <anderssonpublic@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/jdkandersson/OpenAlchemy"
repository = "https://github.com/jdkandersson/OpenAlchemy"
documentation = "https://openapi-sqlalchemy.readthedocs.io/en/latest/index.html"
keywords = ["OpenAPI", "SQLAlchemy", "Python", "models", "database"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Natural Language :: English",
    "Topic :: Database",
    "Topic :: Database :: Front-Ends",
    "Topic :: Internet",
    "Typing :: Typed",
]
include = ["open_alchemy", "*.json", "*.j2"]
exclude = ["docs", "examples", "tests"]
packages = [
    { include = "open_alchemy" },
]

[tool.poetry.scripts]
openalchemy = "open_alchemy.cli:main"

[tool.poetry.dependencies]
python = "^3.7"
SQLAlchemy = "^1.0"
jsonschema = "^3"
Jinja2 = "^2"
sqlalchemy-stubs = "^0.3"
typing_extensions = { version = "^3.7.4", python = "<3.8" }

[tool.poetry.extras]
yaml = ["PyYAML"]
wheel = ["wheel"]

[tool.poetry.dev-dependencies]
pylint = "*"
mypy = "*"
pydocstyle = "*"
black = "*"
pre-commit = "*"
isort = "*"
Sphinx = "*"
doc8 = "*"
connexion = {version = "*", extras = ["swagger-ui"]}
Flask-SQLAlchemy = "*"
alembic = "*"
rstcheck = "*"
bandit = "*"
pytest = "*"
pytest-cov = "*"
pytest-flake8 = "*"
pytest-flask = "*"
pytest-flask-sqlalchemy = "*"
pytest-randomly = "*"
PyYAML = "*"
typeguard = "*"
sqlalchemy_mixins = "*"
wheel = "*"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
