openapi: "3.0.0"

info:
  title: Test Schema
  description: API to illustrate OpenAlchemy using namespaced extension properties (x-open-alchemy* instead of x-*).
  version: "0.1"

paths:
  /employee:
    get:
      summary: Used to retrieve all employees.
      responses:
        200:
          description: Return all employees from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Employee"

components:
  schemas:
    Employee:
      description: Person that works for a company.
      type: object
      x-open-alchemy-tablename: employee
      properties:
        id:
          type: integer
          description: Unique identifier for the employee.
          example: 0
          x-open-alchemy-primary-key: true
          x-open-alchemy-autoincrement: true
        name:
          type: string
          description: The name of the employee.
          example: David Andersson
          x-open-alchemy-index: true
        division:
          type: string
          description: The part of the company the employee works in.
          example: Engineering
          x-open-alchemy-index: true
        salary:
          type: number
          description: The amount of money the employee is paid.
          example: 1000000.00
      required:
        - name
        - division
