
openapi: "3.0.0"

info:
  title: Test Schema
  description: API to illustrate One to Many Relationships.
  version: "0.1"

paths:
  /supervisor:
    get:
      summary: Used to retrieve all supervisors.
      responses:
        200:
          description: Return all supervisors from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Supervisor"
  /employee:
    get:
      summary: Used to retrieve all employees.
      responses:
        200:
          description: Return all employees from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Employee"

components:
  schemas:
    Supervisor:
      type: object
      x-tablename: supervisor
      properties:
        id:
          type: integer
          description: Unique identifier for the supervisor.
          example: 0
          x-primary-key: true
          x-autoincrement: true
          readOnly: true
        name:
          type: string
          description: The name of the supervisor.
          example: David Andersson
    Employee:
      type: object
      x-tablename: employee
      properties:
        id:
          type: integer
          description: Unique identifier for the employee.
          example: 0
          x-primary-key: true
          x-autoincrement: true
          readOnly: true
        primary_supervisor:
          $ref: "#/components/schemas/Supervisor"
        secondary_supervisor:
          $ref: "#/components/schemas/Supervisor"
