openapi: "3.0.0"

info:
  title: Test Schema
  description: API to illustrate OpenAlchemy one to one relationship.
  version: "0.1"

paths:
  /pay_info:
    get:
      summary: Used to retrieve all payment information.
      responses:
        200:
          description: Return all payment information from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/PayInfo"
  /employee:
    get:
      summary: Used to retrieve all employees.
      responses:
        200:
          description: Return all employees from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Employee"

components:
  schemas:
    PayInfo:
      description: Information on how to pay an employee.
      type: object
      x-tablename: pay_info
      properties:
        id:
          type: integer
          description: Unique identifier for the pay information.
          example: 0
          x-primary-key: true
        account_number:
          type: string
          description: The account number to pay the employee into.
          example: David's Account
    Employee:
      description: Person that works for a company.
      type: object
      x-tablename: employee
      properties:
        id:
          type: integer
          description: Unique identifier for the employee.
          example: 0
          x-primary-key: true
        name:
          type: string
          description: The name of the employee.
          example: David Andersson
        pay_info:
          allOf:
            - "$ref": "#/components/schemas/PayInfo"
            - x-backref: employee
              x-uselist: false
