openapi: "3.0.0"

info:
  title: Test Schema
  description: API to illustrate Many to Many Relationships.
  version: "0.1"

paths:
  /project:
    get:
      summary: Used to retrieve all projects.
      responses:
        200:
          description: Return all projects from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Project"
  /employee:
    get:
      summary: Used to retrieve all employees.
      responses:
        200:
          description: Return all employees from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Employee"

components:
  schemas:
    Project:
      description: A large sized business objective.
      type: object
      x-tablename: project
      properties:
        id:
          type: integer
          description: Unique identifier for the project.
          example: 0
          x-primary-key: true
        name:
          type: string
          description: The name of the project.
          example: Expand to the USA
    Employee:
      description: Person that works for a company.
      type: object
      x-tablename: employee
      properties:
        id:
          type: integer
          description: Unique identifier for the employee.
          example: 0
          x-primary-key: true
        name:
          type: string
          description: The name of the employee.
          example: David Andersson
        projects:
          type: array
          items:
            allOf:
              - "$ref": "#/components/schemas/Project"
              - x-secondary: employee_project
          description: The projects the employee is working on.
    EmployeeProject:
      type: object
      x-tablename: employee_project
      properties:
        employee_id:
          type: integer
          x-primary-key: true
          x-foreign-key: employee.id
        project_id:
          type: integer
          x-primary-key: true
          x-foreign-key: project.id
      required:
        - employee_id
        - project_id
