openapi: "3.0.0"

info:
  title: Test Schema
  description: API to illustrate Many to One Relationships.
  version: "0.1"

paths:
  /division:
    get:
      summary: Used to retrieve all divisions.
      responses:
        200:
          description: Return all divisions from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Division"
  /employee:
    get:
      summary: Used to retrieve all employees.
      responses:
        200:
          description: Return all employees from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Employee"

components:
  schemas:
    Division:
      description: A part of a company.
      type: object
      x-tablename: division
      properties:
        id:
          type: integer
          description: Unique identifier for the division.
          example: 0
          x-primary-key: true
        name:
          type: string
          description: The name of the division.
          example: Engineering
    Employee:
      description: Person that works for a company.
      type: object
      x-tablename: employee
      properties:
        id:
          type: integer
          description: Unique identifier for the employee.
          example: 0
          x-primary-key: true
        name:
          type: string
          description: The name of the employee.
          example: David Andersson
        division:
          "$ref": "#/components/schemas/Division"
