name: Code quality checks

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  test-production-test-pypi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYPI_MIRROR:
          - https://test.pypi.org/simple/
          - https://pypi.org/simple/
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: prepare tests
        working-directory: tests/production
        env:
          PYPI_MIRROR: ${{ matrix.PYPI_MIRROR }}
        run: |
          ./prepare.sh
      - name: cache pipenv
        id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: tests/production/.venv
          key: ${{ runner.os }}-pipenv-production-test-pypi-${{ hashFiles('tests/production/Pipfile.lock') }}
      - name: install dependencies
        working-directory: tests/production
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        env:
          PIPENV_VENV_IN_PROJECT: 1
        run: |
          pipenv install --dev
      - name: run tests
        working-directory: tests/production
        run: |
          pipenv run test
